name: Autograding Tests
on:
  push:
  repository_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Test BMI calculator
        id: test-bmi
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test BMI calculator
          setup-command: ''
          command: mvn -B verify --file pom.xml
          timeout: 10
          max-score: 3

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TEST-BMI_RESULTS: "${{ steps.test-bmi.outputs.result }}"
        with:
          runners: test-bmi
